### ISSUE TITLE
Bug installation 

### ISSUE THREAD

**Issue by ipere** [ph4nt0m/binmerge#1]
This project seems super interesting, I tried to compile it but while running
$cmake --build .

I got 
$fatal error: too many errors emitted, stopping now [-ferror-limit=]
$22 warnings and 20 errors generated.

Do you have a fixed version ?

Thanks

**Comment by ph4nt0m** [comment]
I just checked and I don't get any compilation errors. Please provide (at least part of) the actual error messages. Also make sure you are closely following the [build steps](https://github.com/ph4nt0m/binmerge#building-from-source).

What is your build environment (OS, compiler version)?

**Comment by ipere** [comment]
I am on MacOS

**Comment by ph4nt0m** [comment]
I have no possibility to check the building process on MacOS. Windows and Linux are working fine here, though. Unless you give more specific details like those I asked for, I'm afraid I can't help you.

**Comment by ipere** [comment]
/Users/Documents/workspace/binmerge/docopt.cpp/docopt_value.h:76:29: error: 
      union member 'strList' has a non-trivial copy constructor
                        std::vector<std::string> strList;
                                                 ^
/Users/Documents/workspace/binmerge/docopt.cpp/docopt_value.h:103:11: error: 
      function definition does not declare parameters
                Variant variant {};



I will try on Linux then

**Comment by ph4nt0m** [comment]
Those errors are from [docopt.cpp](https://github.com/docopt/docopt.cpp), not `binmerge` itself. Are you using at least

- Clang 3.3 or
- GCC 4.9

as stated on their page?
